### ISSUE TITLE
Can not access to the "Contribution" file. The message from GitHub is:

### ISSUE THREAD

**Issue by Garoverr** [Terminal-DirectMedia-Layer/TDL_Terminal-DirectMedia-Library#2]
' 404 - page not found
The main branch of 
TDL_Terminal-DirectMedia-Library
 does not contain the path 
CONTRIBUTING.md. '

And the same in the both others accessible branches.

**Comment by Shin-gema** [comment]
Hello,
The CONTRIBUTING.md will arrive as soon as possible.I actually work on it.
I will closes this issue when the Contribution is accessible.

**Comment by Shin-gema** [comment]
Hello, 
I close this issue.All the rules for the contribution to the TDL project is now available.
Thanks.
